django/app/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
]

django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.shortcuts import render, HttpResponse
from app.product.sitemaps import ProductSitemap
from app.product.views import index
from app.terms.sitemaps import TermsSitemap

sitemaps = {
    'Product': ProductSitemap,
    'Trems': TermsSitemap, 
}

urlpatterns = [
    # admin
    path('adminpage/', admin.site.urls),
    
    # index
    path('', index, name='index'),

    # apps
    path('product/', include("app.product.urls")),
    path('terms/', include("app.terms.urls")),
    path('order/', include("app.order.urls")),
    path('payment/', include('app.payment.urls')),
    path('cart/', include('app.cart.urls')),
    path('notice/', include('app.notice.urls')),

    # summernote
    path('summernote/', include('django_summernote.urls')),
    
    # sitemap.xml
    path('sitemap.xml', sitemap, {'sitemaps': {'Product': ProductSitemap, 'Trems': TermsSitemap}}, name='sitemap'),

    # 404.html
    path('404.html', lambda request: render(request, '404.html')),

    # robots.txt
    path('robots.txt', lambda request: render(request, 'robots.txt', content_type='text/plain')),

    # naver site verification
    path('naverea9d173cbeb8aac596f5da4df2b85695.html', lambda _: HttpResponse('naver-site-verification: naverea9d173cbeb8aac596f5da4df2b85695.html'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/app/notice/models.py
from django.db import models

class Notice(models.Model):
    title = models.CharField(max_length=99)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

django/app/notice/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Notice

def index(request):
    notices = Notice.objects.order_by('-created_at')

    context = {
        'title': f'공지사항 - 라이프이즈에그',
        'notices': notices
    }

    return render(request, 'notice/index.html', context)

def detail(request, id: int):
    notice = get_object_or_404(Notice, pk=id)
    
    context = {
        'title': f'{notice.title} - 라이프이즈에그',
        'notice': notice
    }

    return render(request, 'notice/detail.html', context)

django/templates/notice/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="mx-auto w-full md:w-5/6 mt-6">
    <p class='text-3xl'>공지사항 - {{ notice.title }}</p>
    <div class='my-4'>
        {{ notice.content|safe }}
    </div>
</div>
{% endblock %}

django/templates/notice/index.html
{% extends 'base.html' %}
{% block content %}
<div class="mx-auto w-full md:w-5/6 mt-6">
    <p class='text-3xl'>공지사항</p>
    {% if not notices %}
    <p class='my-4'>아직 작성된 공지사항이 없어요.</p>
    {% else %}
    <div class='flex flex-col gap-4 my-10'>
        {% for notice in notices %}
        <a href='{% url 'notice:detail' notice.id %}'>
            <div class="h-24 w-full p-4 flex flex-col gap-4 bg-gray_1 rounded-lg">
                <div class='rounded-lg bg-gray_1 h-full'>
                    <div class='flex flex-col justify-center h-full'>
                        <p class='text-2xl'>{{ notice.title }}</p>
                        <p class='text-sm'>{{ notice.created_at|date:'Y.m.d' }}</p>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}